INSERT INTO "ARTICLE" ("CATEGORY","PRIORITY","PRIORITY_VALUE","STATUS","TITLE","TYPE") VALUES('M',2,300,0,'test','EXTERNAL')
INSERT INTO "ARTICLE" ("CATEGORY","PRIORITY","PRIORITY_VALUE","STATUS","TITLE","TYPE") VALUES('M',2,200,0,'test','EXTERNAL')
INSERT INTO "ARTICLE" ("CATEGORY","PRIORITY","PRIORITY_VALUE","STATUS","TITLE","TYPE") VALUES('M',2,100,0,'test','EXTERNAL')